### ISSUE TITLE
[enhancement] Markdown support in dokuwiki 

### ISSUE THREAD

**Issue by Netsaver** [turnermm/ckgedit#140]
Hi, I'm switching from _dokuwiki_ to _markdown_, mainly for standardization and conversion purposes (e.g. _pandoc_ does not support conversion from dokuwiki, there are many different plugins for markdown in _atom_, _brackets_, _chrome_ extensions, etc.).
I've enabled **mardkdowku** plugin, it's not so complete as _markdown-it_  js but it is acceptable.
Anyway I've seen that there is also **markdown  plugin for CKeditor**, but if I add the plugin to the ckgedit plugin and enable it in config.js, then each md sentence is read twice, the former with md source, the latter with rendered md, then if I save and quit ckgedit, this doubled information is present also in the final rendered page.
So, how to enable (if possible) markdown plugin in ckgedit and (if not) could it be possible adding this feature?
Thanks a lot,
Netsaver, Rome (IT)

**Comment by turnermm** [comment]
Well, then,  you've gone one step further than I have, since I don't seem to be successful in getting the markdown plugin to load.  --Unless what is required is that stripped down toolbar definition which is shown on the markdown plugin page.

I have a good deal going on with ckgedit, so even if I could  load this, it wouldn't be a priority.

**Comment by Netsaver** [comment]
Apparently MD is not enabled, as there is no MD button in the toolbar. But despite of this, MD sentences are rendered. I'm not able to understand how they are processed twice...
Anyway, ckgedit is already a nice extension, it would be only a plus.
