### ISSUE TITLE
Captcha Plugins not working with ckgedit

### ISSUE THREAD

**Issue by q2apro** [turnermm/ckgedit#197]
In my testing cases the captcha plugins do not seem to work: 

https://www.dokuwiki.org/plugin:captcha

https://www.dokuwiki.org/plugin:recaptcha2

Could you get them running?

For recaptcha2 the field appears, I answer the captcha question, submit, and there it is again.

**Comment by turnermm** [comment]
On 2016-05-17 7:50 AM, q2apro.com wrote:
> In my testing cases the captcha plugins do not seem to work:
>
> https://www.dokuwiki.org/plugin:captcha
>
> https://www.dokuwiki.org/plugin:recaptcha2
>
> Could you get them running?

No.  The captchas  are attached to the dokuwiki edtor.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by turnermm** [comment]
I'll keep this open for a time when I might  have a chance to examine it more closely.

**Comment by turnermm** [comment]
I got around to this:
https://github.com/turnermm/ckgedit/archive/captcha.zip
I was able to attach the capatcha to ckgedit. 
I hope you wlll be able to test this out so that I can have some input before I merge it into the master.  I've disabled several buttons, the ``DW Edit`` button, which conflicts with the captcha plugin and the ``Edit Fonts`` button.

**Comment by turnermm** [comment]
I've been working on this and it seems ready to go.  I've solved the DW Edit button problem, and with ckgedit you get acl control over when the captcha appears. In any event, since you haven't come back to me on this, I will close the issue.  You can always reopen.
