### ISSUE TITLE
Farm Installation: Problems with media upload

### ISSUE THREAD

**Issue by simon-roderus** [turnermm/ckgedit#214]
I run a DokuWiki farm installation (using the .htaccess method). Today I installed the farm version of the ckgedit plugin. For one animal wiki I  ...
- edited animal/conf/local.php to include $conf['animal'] and $conf['animal_inc']
- created a subfolder in ckgedit/fckeditor for the wiki and added links for "media", "image", and "file" that link to the animal's media-directory (I did not use hardlinks, should I?).

Now the new editor works as expected, but the media-button seems to be broken and shows a wrong directory. It looks like this:
![file browser](https://cloud.githubusercontent.com/assets/9551133/16237903/a59df082-37de-11e6-83b1-3ba1b2efa446.PNG)

Any idea how to fix this problem?

**Comment by turnermm** [comment]
I'm afraid that image doesn't tell me anything, It looks fine.

 Have you read: https://www.dokuwiki.org/plugin:ckgedit#htaccess_method?  I've just edited it a bit to hopefully make things clearer. And since you seem to have already had a farm set up before installing ckgedit, you have to manually add the two $conf options as indicated there.

**Comment by turnermm** [comment]
Sorry, I see you did update $conf

**Comment by proxymus** [comment]
I had this problem too. 
Do you have the link files in the dokuwiki/lib/plugins/ckgedit/fckeditor/userfiles folder?
![2016-06-22 08_09_49 media](https://cloud.githubusercontent.com/assets/1539498/16256228/d8e77888-3850-11e6-9d0f-a84adb08ef06.png)
They should link to the dokuwiki/data/media folder.

In the /var/www/dokuwiki/lib/plugins/ckgedit/fckeditor folder you should have a folder for each animal and within this folder you should have the links to the animals data/media folder.

Also be sure that you don't have a cache problem -> use a new private browser window for testing.

**Comment by simon-roderus** [comment]
@turnermm and @proxymus: thank you both for your helpful advice, I appreciate that a lot! I already had links for my animal but not for the userfiles. I now also added links for the userfiles, but the media manager is still broken. The cause of my problems might be, that at the time I first ran the ckgedit-plugin the ckgedit folder was owned by root (instead of www-data) and because of that the plugin failed to create some folders and links. There also were some warning messages about the failed creation of files or links. Of course, I did set the correct owner and privileges after that happend.

I just uploaded an image using the FCKeditor media uploader at an animal called "test". The upload did work but the image arrived at the farm's media directory and not at the animal's media directory. The preview of the image in the media uploader also seems to be broken.

Here are some more details about my configuration.

Filesystem
```
/srv/www/dokuwiki/ (farm)
/srv/www/wiki/test (animal)
```

The animal's config (local.php) containts:
```
$conf['animal'] = 'test';
$conf['animal_inc'] = '/srv/www/wiki/test/';
```

/srv/www/dokuwiki/lib/plugins/ckgedit/ckgedit/fckeditor/userfiles looks like this ...
![a](https://cloud.githubusercontent.com/assets/9551133/16275037/95be7acc-38a8-11e6-8ac7-773fb6d3500c.PNG)

/srv/www/dokuwiki/lib/plugins/ckgedit/ckgedit/fckeditor/test looks like this ...
![b](https://cloud.githubusercontent.com/assets/9551133/16275046/9fa03fa8-38a8-11e6-9402-ce4d91b2a68a.PNG)

**Comment by turnermm** [comment]
> /srv/www/dokuwiki/lib/plugins/ckgedit/ckgedit/fckeditor

The path looks incorrect.  It should be ``/srv/www/dokuwiki/lib/plugins/ckgedit/fckeditor``

**Comment by simon-roderus** [comment]
Thank you for your fast response. My path above had a typo, sorry! It already is `/srv/www/dokuwiki/lib/plugins/ckgedit/fckeditor`.

**Comment by turnermm** [comment]
Is it  possible that you have an error in your redirection rules in your barn's .htaccess file:
```
RewriteEngine On
RewriteRule ^/?([^/]+)/(.*)  /farmer/$2?animal=$1 [QSA]
RewriteRule ^/?([^/]+)$      /farmer/?animal=$1 [QSA]
Options +FollowSymLinks

```
In your case wiki/.htaccess.  Because for some reason the redirection isn't working.

**Comment by turnermm** [comment]
@turnermm and @proxymus: thank you both for your helpful advice, I appreciate that a lot! I already had links for my animal but not for the userfiles. I now also added links for the userfiles, but the media manager is still broken. The cause of my problems might be, that at the time I first ran the ckgedit-plugin the ckgedit folder was owned by root (instead of www-data) and because of that the plugin failed to create some folders and links. There also were some warning messages about the failed creation of files or links. Of course, I did set the correct owner and privileges after that happend.

I just uploaded an image using the FCKeditor media uploader at an animal called "test". The upload did work but the image arrived at the farm's media directory and not at the animal's media directory. The preview of the image in the media uploader also seems to be broken.

Here are some more details about my configuration.

Filesystem

/srv/www/dokuwiki/ (farm)
/srv/www/wiki/test (animal)
The animal's config (local.php) containts:

$conf['animal'] = 'test';
$conf['animal_inc'] = '/srv/www/wiki/test/';
/srv/www/dokuwiki/lib/plugins/ckgedit/ckgedit/fckeditor

**Comment by turnermm** [comment]
I hate to ask the obvious but are you using the farms version of ckgedit?

**Comment by turnermm** [comment]
Closed by error, I'm on my phone

**Comment by simon-roderus** [comment]
@turnermm Thank you for your advice, with your help I finally solved it and now it works like a charm.

Those two things were wrong:
- I used the farm version of ckgedit, but made some copy & paste error while installing it. The result was that there actually was a ckgedit folder inside the ckgedit (so somehow I managed to duplicate the plugin into it's own base folder).
- the second error was, that the `plugin»ckgedit»winstyle` was accidentally enabled. 

Now the editor works and I already begin to love it. This plugin will enable many of our not so tech-savvy users to edit our wiki for the first time (right now they only read in it). It also seems to improve my editing speed in most scenarios, although I still prefer the build-in editor for specific cases. Because of that I really like that changing the editor is so easy!

@turnermm 
Thanks again for your great help. Your help encouraged me to search for the error and not to give up! I also want to thank you for all the work and time that you had, have and will put into this and other plugins!
