### ISSUE TITLE
Issue with links in headers

### ISSUE THREAD

**Issue by stevenmg** [turnermm/ckgedit#232]
Not sure if this is a common issue or not, but if I place a link in a header it displays the link shortcode as a header rather than a functional link.
![link to header](https://cloud.githubusercontent.com/assets/3642158/18401381/442c9d04-76a8-11e6-8f16-d750dd69a682.PNG)

**Comment by turnermm** [comment]
This question comes up periodically on the forum.  While the CKEditor lets you place markup in headers, Dokuwiki doesn't.  Dokuwiki simply treats it as text.  

In the Editor:
![headers_with_markup](https://cloud.githubusercontent.com/assets/176447/18410710/8a89c282-772e-11e6-8459-d0c8fc3ccc3a.png)

In the browser:
![headers_markup_result](https://cloud.githubusercontent.com/assets/176447/18410711/8d8e33aa-772e-11e6-9fee-b4efc9e23428.png)

In the Dokuwiki saved file:
```
===== I want superscript <sup>text </sup>in my header =====

I want superscript <sup>text </sup>  in my header

```

**Comment by turnermm** [comment]
Already in place was a regex that captured and removed markup that included headers within the markup's tag: `**BOLD HEADER**`.  I fixed the header regex so that now it will capture things like `===== I want superscript <sup>text </sup>  in my header =====`,  where the markup is internal to the header.  But I haven't removed links.  Dokuwiki doesn't allow markup inside links, but will accept markup external to the links.  So you can't use:  `[[internal_link|**internal link**]]` but you can use `**[[internal_link|internal lnk]]**`.

**Comment by stevenmg** [comment]
Would it be possible to run some regex before save and then throw a warning so the user is made aware of the issue and given an option to fix it before saving?

**Comment by turnermm** [comment]
Should be able to do that.  Currently all text-based markup is filtered out, with user notified. 

On my phone, back later.

**Comment by turnermm** [comment]
I've done, the same as with the text-based markup, and filtered out the links.  Then a notice is posted after the save.  This method is fine with text markup, like bold, etc, but I realize this isn't ideal with links, so I'll look at something less frustrating to the user.

**Comment by stevenmg** [comment]
Ideally the user would have to confirm before removing something as critical as links, but simply removing them with a notice is definitely better than nothing.
