### ISSUE TITLE
Save button not working when behind reverse proxy

### ISSUE THREAD

**Issue by FrankIJskes** [turnermm/ckgedit#233]
When dokuwiki is behind a reverse proxy (nginx in my case), the save button does not work out of the box.

Solution: inside the dokuwiki configuration set the baseurl setting to the outside url. This fixes all "false" and other problems using this plugin.
(this is mainly a documentation issue)

**Comment by turnermm** [comment]
Thank you.  I'll include this in the documentation.  As an additional bit of information, a contributor has upgraded ckgedit, so that it  has access to both the current CKEditor file browser and the native Dokuwiki linkiwiz and filebrowser. 
https://github.com/turnermm/ckgedit/archive/stvg.zip
Here is the discussion: 
https://github.com/turnermm/ckgedit/pull/230
I haven't had any experience with reverse proxy but it's possible that DW picks this up automatically.

**Comment by FrankIJskes** [comment]
I was triggered by the fact that ckgedit won't enable the save button 
when it is embedded. I did not debug, but it might make an incorrect 
check when the page has a different name then dokuwiki says it is. Since 
it is a dokuwiki configurable setting i do not mind.
I found more things not working, but i haven't had the time to debug it 
to the end.

Thanks for updating the docs and i also updated the editor and it still 
works :).

Frank

**Comment by turnermm** [comment]
Haven't gotten to the docs yet but will do

Get Outlook for iOS




On Tue, Sep 13, 2016 at 3:16 AM -0500, "FrankIJskes" <notifications@github.com> wrote:












When dokuwiki is behind a reverse proxy (nginx in my case), the save button does not work out of the box.



Solution: inside the dokuwiki configuration set the baseurl setting to the outside url. This fixes all "false" and other problems using this plugin.

**Comment by turnermm** [comment]
Done: https://www.dokuwiki.org/plugin:ckgedit#reverse_proxy
(Gave your github id credit for the fix.  Feel free to delete it if you don't want it there)
