### ISSUE TITLE
Problem with media upload

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#241]
Hi,

attempting to upload media by the fckeditor-mediamanager fails with this error message:
```Error creating folder "/var/www/html/wiki/lib/plugins/ckgedit/fckeditor/userfiles/image/" (mkdir(): File exists)```
What can I do?

Regards
Juergen

**Comment by turnermm** [comment]
This happens when the file browser does not have symlinks in the `userfiles` directory.  So check `userfiles` and delete the `image` directory and create symlinks to `data/media` for `file` and `image`.   If you are not familiar with this, see the instructions for creating symlinks in the docs for using an [alternate save directory](https://www.dokuwiki.org/doku.php?id=plugin:ckgedit#configuration_and_set-up) on the ckgedit plugin page.
