### ISSUE TITLE
Would it be possible to merge farm branch with the master

### ISSUE THREAD

**Issue by proxymus** [turnermm/ckgedit#243]
Hello,
I really appreciate the plugin and the latest enhancements. In our environment we use the farm branch. Do you see any chance to merge the farm branch with the master branch? Maybe it could be done with a config option?

Thank you in advance.

Kind regards 
Proxymus

**Comment by turnermm** [comment]
Not really.  I just finished syncing the farms branch with the latest master.  Don't throw out your current version but install the update.  It seems fine.

**Comment by proxymus** [comment]
Is the file browser enhancement included in the current farm branch? Because I've the old file browser still.  Do I've to configure anything?

Thank you in advance.

**Comment by turnermm** [comment]
No, it's not, if you mean the one which I've code names ckgdoku and uses the Dokuwiki media manager.  I didn't work on that myself and in my tests I see that it doesn't successfully insert images.

**Comment by turnermm** [comment]
You could try ckgdoku in a test situation and then open an issue in ckgdoku (not ckgedit) starting that you are using it with farms and detailing your experience. That will put it on record.

**Comment by proxymus** [comment]
Thank you for updating the farm branch so quick. I will set up a test environment and then I will test the ckgdoku branch.

**Comment by turnermm** [comment]
I was checking the update and saw that I hadn't synced the newest language files, including the default English.  So this is in the latest update to github.

**Comment by turnermm** [comment]
Some further updates, in particular to language files which I missed in my earlier update

**Comment by proxymus** [comment]
Fantastic. Thank you again for your work!

**Comment by turnermm** [comment]
By the way -- You need the most recent distro of dokuwiki:  Elenor Of Tsort (2016-06-26) or later -- to run ckgdoku.

**Comment by proxymus** [comment]
Thank you for providing the updates. I've tested the ckgdoku farm branch and I've noticed some problems with inserting images. When I insert an image with the dokuwiki file browser I see the image in the select dialog, but in the preview dialog it disappears. When I save the page the image is displayed.
I've made my test in a private browser session to exclude caching problems. I've made this test for two animals and both have this problem.

**select dialog**

![2016-10-24 08_04_46-ckgdoku_farm](https://cloud.githubusercontent.com/assets/1539498/19635353/fb00429c-99c1-11e6-98cc-9759369564ba.png)

**image preview**

![2016-10-24 08_10_11-ckgdoku_farm](https://cloud.githubusercontent.com/assets/1539498/19635354/fb01f13c-99c1-11e6-88cf-1ea8551fd493.png)

**editing the article**

![2016-10-24 08_11_06-ckgdoku_farm](https://cloud.githubusercontent.com/assets/1539498/19635356/fb33b3f2-99c1-11e6-8422-e0138f16262d.png)


**image in the saved page**

![2016-10-24 08_11_29-ckgdoku_farm](https://cloud.githubusercontent.com/assets/1539498/19635355/fb13599a-99c1-11e6-9dfc-3d7614d019fe.png)

One additional question. In your post above you had inserted the same link two times. Which is the current farm branch for **ckgedit**?

https://github.com/turnermm/ckgedit/tree/farms_4.7a
**or**
https://github.com/turnermm/ckgedit/tree/farms_4.7

Which should I test? I assume the 4.7a version - right?

**Comment by turnermm** [comment]
4.7a has the most recent updates. 

The problem you are having is related to the .htacess files.  You have to have an .htaccess file in each farm's media directory that enables access to the directory.  That would be either an .htaccess based on .htaccess.open or .htaccess.security, which are found in fckeditor/userfiles.  Dokuwiki circumvents these restrictions because it doesn't access media files through a web address but through its internal media  application, fetch.php.  There are other ways of handling this if you have a lot of animals. You can place these .htaccess files in the fckeditor directory, but if you use .the htaccess.security version in fckeditor, then in fckeditor/editor you must put .the htaccess.open version. (Of course you must always rename these .htaccess).  After these changes you should empty the cache in your browser and possibly your installation of dokuwiki.
