### ISSUE TITLE
JS error when running DokuWiki with ckgedit in an iframe

### ISSUE THREAD

**Issue by waschinski** [turnermm/ckgedit#250]
We are running DokuWiki in an iframe within our homepage. When installing and activating the ckgedit plugin we get an JS error:

`TypeError: top.ckgedit_language_chk is not a function`

We tracked down the error in config.js where _**top**_ is no longer the DokuWiki window which the plugin seems to refer to. By definition _**top**_ is the topmost browser window of the current window which is not the case when running DokuWiki in an iframe.

Our fix for now is to add the following code to config.js at the very top:

`var top = window.self;`

This way the the plugin seems to work fine even when running DokuWiki in an iframe.

Edit: I just found a similar issue #33 where the user was solving the problem by assigning an ID to the iframe and reference that in config.js. I would rather see a general solution which could be added to the repository so in the future one would not have to change the plugin code manually. So would there be any downside by using _window.self_ instead of _top_?

**Comment by turnermm** [comment]
Thanks.    I've referenced your solution on the ckgedit plugin page: [installing_in_an_iframe](https://www.dokuwiki.org/plugin:ckgedit#installing_in_an_iframe)

It's been some time since this question arose.  It was very difficult to do with fckgLite, but I can't recall anyone installing ckgedit in an IFRAME.
