### ISSUE TITLE
no preview in mediafile browser

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [turnermm/ckgedit#257]
Although the mediafile browser shows the media structure and the inclosed files the preview doesn't function. I've copied the .htaccess file to the media directory with no success.

Regards Juergen

**Comment by turnermm** [comment]
I need more information.  First, which ,htaccess.  Secondly, what is the Operating System on which your dokuwiki is running?  Are you using the unix-style (via userfiles) or the Windows style access to the file browser ?  Are you running your own apache server?  Are you on a shared hosting service?   And what is not functioning: only the preview in the image dialog or the image listings in the file browser itself?  Can you access media files using the internal media choice in the link dialog?

**Comment by fschaeffer** [comment]
I can confirm that on newest dokuwiki Release 2017-02-19a "Frusterick Manners" the ckgedit plugin 2017-02-18 does not display images in windows style media list (broken image displayed) and also it is not possible to select the media files and use them in the editor. The popup uses the plugins directory as starting point instead of using the web servers document root.

I also tried https://github.com/turnermm/ckgdoku/archive/master.zip which looked better but when opening the media file window no folders are available for selection and no images are displayed.

Funny note, using the window I am able to upload files...

The dokuwiki media manager displays everything as it should be.

Linux, lightHttp, chroot

**Comment by turnermm** [comment]
There must be something faulty in your configuration.  I  have been using Frusterick Manners on several wikis with different configurations without any issues, including a test farm.  See: [mturner.org](http://www.mturner.org/devel/playground/fmanners)

**Comment by turnermm** [comment]
I have no experience with this configuration:  lightHttp, chroot.  So can't be of help there.

**Comment by Juergen-aus-Koeln** [comment]
I have installed your new  ckgdoku distribution, and everything works fine now

**Comment by turnermm** [comment]
Something to be aware of.  When loading an image into the preview pane, the image size has only one dimension, width, I believe, because Dokuwiki stipulates onlyh one dimension when loading an image.  You must click on the resize button next to the dimensions (the curved arrow) to get the actual size.
