### ISSUE TITLE
False Link

### ISSUE THREAD

**Issue by taizoli** [turnermm/ckgedit#265]
ckgedit installed Version:  2017-02-25; DokuWiki "Elenor Of Tsort" 

Hello,

i have detected a bug. When i create an internal link and save the site, ckgedit alter this automatically into an external link (URL).

so from this one: test:testsite (internal link)
into this one: http://dokuwiki.xy/doku.php?id=:test:testsite (external link)

could you please help?
Thank you.

Best regards
Zoltan Horvath

**Comment by turnermm** [comment]
Can't reproduce this.  We had the reverse of this a week or so ago, where external links could be mistaken for internal but noone has ever reported this. Adn since this is so fundamental to the workings of ckgedit and dokuwiki, it should  have shown up by now.  So, I will need a lot more information. When does it happen?   Does it always happen?  What version of ckgedit?   How did you install and configure ckgedit? Can you give me some screen shots?

**Comment by taizoli** [comment]
I have two systems one PROD and one TEST. The problem appears on both of them and every time when i create an internal link and save the site. Version what i use is the latest "ckedit_457-17-Feb_25-15_39"
Befor this version, this problem doesn't occurred. I have normally istalled ckgedit through plugin manager and updated from the previous release. I didn't alter anything in config.
![dokuwiki_test1](https://cloud.githubusercontent.com/assets/18721085/23469267/78146e16-fea3-11e6-8e03-72e12307f4d2.png)
![dokuwiki_test2](https://cloud.githubusercontent.com/assets/18721085/23469266/78104386-fea3-11e6-9fc1-e24a69835323.png)

**Comment by turnermm** [comment]
The issue appears to be a side-effect of the fix made for  #263 and the fact that (I assume) you use canonical urls.  I created a test branch with an update for this problem:
   https://github.com/turnermm/ckgedit/archive/extern_id_fix.zip
Please try it and let me know if your have success.

**Comment by taizoli** [comment]
Super, it worked.
Thank you
