### ISSUE TITLE
Upload browser will show wrong list

### ISSUE THREAD

**Issue by qwe852147** [turnermm/ckgedit#312]
I have a trouble about Upload browser.

Step: 

1. click insert link button  select internal-link   
2. click browser to open Resources Browser  
![01](https://user-images.githubusercontent.com/10329643/27374559-dcb26082-569e-11e7-9169-56f786984657.png)
3. click close window 
![02](https://user-images.githubusercontent.com/10329643/27374570-e63cd290-569e-11e7-945f-6a78cfedb521.png)
4. click cancel button
![03](https://user-images.githubusercontent.com/10329643/27374684-4ad56686-569f-11e7-9409-74c884181c2b.png)
5. click upload image 
![04](https://user-images.githubusercontent.com/10329643/27374691-500f371c-569f-11e7-8d0b-41da373bbe40.png)
6. click browser to open Resources Browser
the content of Resources Browser will wrong. it will show page in list not image
![05](https://user-images.githubusercontent.com/10329643/27374709-66148472-569f-11e7-9b1e-3cc43ad2ef6c.png)

It will not happen in first you might do this twice or more

**Comment by turnermm** [comment]
I have not been able to reproduce this error.  If your dokuwiki is running on a linux server, set the winstyle option to true.  If it is on a windows server, set the nix_style setting to true.  In the latter case, you need a set of symbolic links, which is described here:  
https://www.dokuwiki.org/plugin:ckgedit#alternate_save_directory
The ckgedit plugin attempts to create these for you, but may fail because of permission.  When creating these links yourself, you may need to run the command prompt as administrator .

**Comment by qwe852147** [comment]
Thanks! I have tried it but not anything change.The wrong is still exist.
I 'll check it what cause it
