### ISSUE TITLE
Don't save on DW Edit button

### ISSUE THREAD

**Issue by iainhallam** [turnermm/ckgedit#331]
I frequently need to change to the DokuWiki editor to do some hand editing of complex markup, and so I find myself clicking DW Edit a lot. I typically do this immediately after wanting to edit the page, so no changes have been made, but when I click the button, ckgedit immediately saves, sometimes destroying HTML and adding extra backslashes to the end of the document. It also changes / to : in Wiki links, which annoys some users no end!

Can ckgedit be set not to save if there are no changes in the buffer, please?

**Comment by turnermm** [comment]
That was fixed 3 years ago.

**Comment by turnermm** [comment]
I did a quick check and see that the by-pass is not functioning in the latest Chrome.  There are two solutions.  One is to install the dwedit plugin, which will give you an additional icon that will let you switch directly into the dokuwiki editor.  It opens the entire pare, however,  If you want to edit a section, then you can just double-click on that section and it will open in the dokuwiki editor.    

Otherwise switch to Firefox or if you are using Windows, switch to either Edge of IE.

**Comment by turnermm** [comment]
This branch of ckgedit has a work-around for the Chrome issue: 
     https://github.com/turnermm/ckgedit/archive/chrome_fix.zip
This had been a problem prior to Chrome 26 ago but then the problem disappeared because of changes in Chrome.  But it seems they've reverted. 

As for your HTML being corrupted by these auto-saves, these saves should be no different from any other saves.   There is a great deal of documentation for ckgedit on the dokuwiki.org web site.  Check there for possible solutions.  The back-slashes are simply  line-breaks.   But if your dokuwiki markup is so complex and demanding, then maybe you shouldn't be using ckgedit at all.

And if it converts  ` / to : in Wiki links`, then that should be reported as a separate issue with more information about where and how, which browsers, etc.
