### ISSUE TITLE
Cannot add images

### ISSUE THREAD

**Issue by idogal** [turnermm/ckgedit#336]
Hello,

using the last version (2017-09-24), I cannot see the selected image in the "image properties" windows, nor can I see them in the "browse" dialog. I also cannot choose the "OK" button - it just doesn't do anything. I can only cancel.

Would appreciate any ideas or suggestions.

Thank you

![image](https://user-images.githubusercontent.com/15966812/30956070-96d6add2-a43e-11e7-9a6b-7ae02d6a7c8e.png)
 
![image](https://user-images.githubusercontent.com/15966812/30956089-ab361b8c-a43e-11e7-8ff3-8120508c919b.png)

**Comment by turnermm** [comment]
If your web server is  linux, then try setting the winstyle option to true.  If windows, then set the nix option to true; however, you will have to create symlinks in the fckeditor/userfiles directory to  the media directory.  See this for how-to:
   https://www.dokuwiki.org/plugin:ckgedit#alternate_save_directory

Do you know what your previous version was?  because there is nothing in 9/24 that would account for this problem.

**Comment by idogal** [comment]
Enabling _winstyle_ fixed the problem. Thank you.

I'm not sure what the previous version was, sorry.
