### ISSUE TITLE
PHP crash in save.php

### ISSUE THREAD

**Issue by martbart** [turnermm/ckgedit#351]
Hi Mr. Turner,

On an up-to-date dw install, after updating ckgedit, ckgedit crashes when saving the page, resulting in a beautiful white page.

PHP Fatal error:  Using $this when not in object context in  /lib/plugins/ckgedit/action/save.php on line 188
14170 bytes, Nov 13 18:31 /lib/plugins/ckgedit/action/save.php

Restored this older version of ckgedit and that did save the same test-page.
9929 bytes, Aug 27 05:33 /lib/plugins/ckgedit/action/save.php

The page that caused the crash has code blocks and dw link code inside. The page contains text like "{{ links here }}" and real dw links to "non dokuwiki files" . Server is an older centos machine with php 5.3.3.

**Comment by turnermm** [comment]
Dokuwiki requires PPH 5.6 or later: https://www.dokuwiki.org/requirements
`$this` is acceptable in anonymous functions since PHP 5.4: http://php.net/manual/en/functions.anonymous.php#example-167.   Which Centos are yoouo using?
You may end up running into problems like this elsewhere, without an upgrade to 5.6.  It is  possible to upgrade PHP from Centos 6.

**Comment by martbart** [comment]
Allright, thanks. I see what went wrong, I used the Dokuwiki PHP check (http://server/dokuwiki/?do=check) that shows 5.3.3 being ok for DokuWiki version: Release 2017-02-19e "Frusterick Manners".
I will use newer php.
