### ISSUE TITLE
useheading option isn't considered when inserting internal wiki link

### ISSUE THREAD

**Issue by solewniczak** [turnermm/ckgedit#353]
The wiki link in the WYSIWYG editor is always inserded with it's page id even if the useheading option is set. I believe it's due to wrong implementation of _useHeading_ function in _ckeditor/plugins/link/dialogs/link.js.unc_:
```
var useHeading = function(wiki_id) {
        var retv = wiki_id;
        
         jQuery.ajax({
             method: "POST",
             url: DOKU_BASE + 'lib/exe/ajax.php',
             data: {             
             dw_id: encodeURIComponent(wiki_id),
             call: call="use_heads"
             },                           
           async: true,
            dataType: "html",
              })
            .done(function(data)
              {
               retv = decodeURIComponent(data);  
              })
              .fail(function(jqXHR, textStatus, errorThrown )
              {
                alert('Error: ' + textStatus +'/' + errorThrown);
                
              })
             .always (function (data, textStatus, errorThrown)
             {

    });
          
    return retv;
};
```
Since the ajax call is asynchronous, the function will always return wiki_id. I believe that it's quite straightforward to fix and I can do it but I need instructions how to build ckeditor from it's sources.

**Comment by turnermm** [comment]
This is true.  But it has to be  asynchronous, in order to conform to current browser and jQuery requirements.  So unless I find  way around this, it will eventually have to be removed from the CKEditor side of ckgedit and left to save.php. If you have any ideas, I'd be glad to see them.

I've never totally built CKEditor from its sources.  I use the current full distribution and get the source code I need from github at CKEditor's  development branch.   And then either write my own plugins or modify theirs.  link.js.unc is the original version 3 CKEditor plugin modified for use with dokuwiki.    (CKEditor is now moving to version 5.)

**Comment by solewniczak** [comment]
But how to make ckeditor/plugins/link/dialogs/link.js.unc be launched by dokuwiki? Simple file modification doesn't work.

**Comment by turnermm** [comment]
I'm not sure what you have in mind.  `link.js.unc` is the uncompressed version of `link.js`, and that can only be loaded by the ckeditor for it to be integrated into the editor.

**Comment by solewniczak** [comment]
Ok, how to compress `link.js.unc` after modifying it?
