### ISSUE TITLE
Option to use plain text paste by default

### ISSUE THREAD

**Issue by nilssiegle** [turnermm/ckgedit#380]
It would be very helpful for admins to have an option to force plaintext paste.
If users copy & paste text from websites or Word they often dont use the option from the toolbar, and mess up the whole page.
Having a copy & paste behaviour like in the standard DW Edit would really reduce this risk.

**Comment by turnermm** [comment]
That is not a ckgedit-level decision. It is built into the CKEditor.  But there is  the paste as plain text toolbar item:
![pasteasplaintext](https://user-images.githubusercontent.com/176447/36352778-aefeff12-1483-11e8-8068-95b41c147344.png)

**Comment by nilssiegle** [comment]
Thanks for your fast reply.
I know the toolbar item, I mentioned it above in the initial post. My problem are users that are either to lazy or to stupid to use that function. But I will adress that issue at the CKEdit repo, thank you for clarifying the responsibilities.

**Comment by MrReSc** [comment]
@nilssiegle did you found a solution to force plain text pasting?

**Comment by turnermm** [comment]
I have removed the text paste toolbar items because recent browsers now want you to use Ctrl-V, or Command-V (on Macs) for pasting. As I said earlier, this is in the control of the CKEditor, and there's nothing I can do about it myself.

**Comment by MrReSc** [comment]
I get that. Do you know a way to force paste as plain text? 
I have the same problem that users are usually too lazy to remove Word formatting.

**Comment by turnermm** [comment]
I don't have a solution for that; I'll think about it.  Maybe I can come up with something.

**Comment by MrReSc** [comment]
Thank you for your efforts. Possibly the plugin https://ckeditor.com/cke4/addon/pastetext would be a possibility.

**Comment by MrReSc** [comment]
Or maybe this config works: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-forcePasteAsPlainText

**Comment by turnermm** [comment]
You can do that for yourself, if it works for you, but it's not for everyone.  Try this:
https://github.com/turnermm/ckgedit/archive/textpaste.zip

**Usage:**
Open the Geshi app in the toolbar and paste your text into the geshi tool's window.  From the geshi types menu, select `text` or simply type `text` into the textbox. Click OK.  When the file is saved, the formatting will be removed.  Let me know if it works for you.

**Comment by MrReSc** [comment]
Thank you for your solution.
Unfortunately Geshi as an intermediate step is not an option for my users. Most of them are used to MS Word.

But I also tried something else. I changed the two configuration parameters in the file ``config.js`` to true.
```
config.pasteFromWordRemoveFontStyles = true; // preserve font style when "paste from word"
config.pasteFromWordRemoveStyles = true; // preserve style (color) when "paste from word"
```
Don't forget to empty the browser cache.

That partially solves my problem. Fonts and colors are no longer copied. The headings of Word, however, are still there.

I also tried ``config.forcePasteAsPlainText = true;``, but it didn't work. Probably because of the ``config.allowedContent=true;`` parameter.  But if I set it to ``false`` then no more images can be pasted with ``CTRL + V``.

I will read myself into [Content Filtering (ACF)](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html), maybe I will reach my goal with it.

**Comment by MrReSc** [comment]
I've found a solution.

Actually only ``config.forcePasteAsPlainText = true;`` has to be commented out twice in ``config.js``. So the [Content Filtering (ACF)](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) is set to [automatic](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html#automatic-mode).

Since I disabled font color, size and font style in CKGedit settings, ACF removes these formattings. But the headings are retained. More examples can be found [here](https://ckeditor.com/docs/ckeditor4/latest/examples/acf.html).

@turnermm, I think this should be the default for CKGedit.

**Comment by nilssiegle** [comment]
@MrReSc that config option seems like a good idea, I'll try that if I have time.
