### ISSUE TITLE
Can't switch to CKGEditor with dw_priority set

### ISSUE THREAD

**Issue by mrclschstr** [turnermm/ckgedit#382]
My error behavior is pretty the same to https://github.com/turnermm/ckgedit/issues/123. The cookie `FCKG_USE` is always `_false_` in my browser. As a result I can't switch back to the default editor when the option `dw_priority` is set. Without setting this option I can switch back and forth as I like.

I'm using the current version of Dokuwiki (2017-02-19e "Frusterick Manners") on a Windows Server 2012 R2 with IIS 8.5 and PHP 7.1. My browser is Chrome 64.0 but this issue also occurs on a current Firefox. Anybody else experiencing this issue?

**EDIT:** Sorry, wrong description. Due to the cookie error I can't switch back to CKGEditor when the option `dw_priority` is set!

**Comment by turnermm** [comment]
Try using the editor priority feature in the Update Profile dialog.

Also, see: https://www.dokuwiki.org/plugin:ckgedit:configuration#dw_users for configuration

**Comment by mrclschstr** [comment]
I just realised my description above was a bit misleading (see edit). The real issue is that I can't switch to the CGKEditor when the `dw_priority` option is set. The cookie `FCKG_USE` is always `_false_`.

Using the Update Profile dialog does not work as well. No matter what editor I chose in the dialog, Dokuwiki is always presenting me the DWEditor and I can't switch to the CGKEditor.

**Comment by turnermm** [comment]
I have no idea about what is happening, since I regularly used dw_priority without any issues, and so can't reproduce it.  But  do have a suggestion.  First, turn off dw_priority and install the dwedit plugin.  This will enable you to get a button or link that will open the entire page in the native dw editor.  Secondly, when in the ckgedit mode, you can double click any section and  that section will open to the native dw editor.  See: [double_click_method](https://www.dokuwiki.org/plugin:ckgedit#double_click_method) at dokuwiki.org.

**Comment by turnermm** [comment]
I would be interested to know what your setup is--which server your dokuwiki is on and which browser(s) you are using.

**Comment by mrclschstr** [comment]
Disabling `dw_priority` and using the dwedit plugin is a suitable alternative for me. Thanks!

As I already marked in my first post: I'm using Dokuwiki on a Windows Server 2012 R2 with IIS 8.5 and PHP 7.1. My browsers are Chrome 64.0 and Firefox 58. You need some more details?
