### ISSUE TITLE
The filemanager show "blank" frame in window. Not show any objects

### ISSUE THREAD

**Issue by pilot513** [turnermm/ckgedit#384]
DokuWiki - last version.
OS: OEL74 with last updates + Apache 2.4 with PHP71 

When i try set "internal link" and filebrowser lunched - it blank ...
https://hostname/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/browser.html?Type=File&Connecto .... foo bar

The dokuwiki opened with FF (last) or Vivaldi (last)

**Comment by turnermm** [comment]
Don't fully understand this, partly language difficulty.  There has never been a problem before reporting an issue getting the internal links to display, not that I can remember.    Maybe you should switch to ckgdoku which gives you the option of using the dokuwiki linkwiz and media manager.

**Comment by pilot513** [comment]
I already cwitch to CKGdoku... But not worked.   When i lanch filebrowser he empty

**Comment by pilot513** [comment]
Why "CKG filebrowser" showed blank panels ?

**Comment by pilot513** [comment]
May be i must downgrade PHP from 71 to 5.x ?
Now installed:
`rh-php71-runtime-1-1.el7.x86_64
rh-php71-php-cli-7.1.8-1.el7.x86_64
rh-php71-php-mysqlnd-7.1.8-1.el7.x86_64
rh-php71-php-process-7.1.8-1.el7.x86_64
rh-php71-php-ldap-7.1.8-1.el7.x86_64
rh-php71-php-zip-7.1.8-1.el7.x86_64
rh-php71-php-common-7.1.8-1.el7.x86_64
rh-php71-php-gd-7.1.8-1.el7.x86_64
rh-php71-php-pdo-7.1.8-1.el7.x86_64
rh-php71-php-xmlrpc-7.1.8-1.el7.x86_64
rh-php71-php-pear-1.10.4-1.el7.noarch
rh-php71-php-7.1.8-1.el7.x86_64
rh-php71-php-intl-7.1.8-1.el7.x86_64
rh-php71-php-json-7.1.8-1.el7.x86_64
rh-php71-php-mbstring-7.1.8-1.el7.x86_64
rh-php71-php-xml-7.1.8-1.el7.x86_64
rh-php71-1-1.el7.x86_64
`

**Comment by pilot513** [comment]
In your video [https://www.youtube.com/watch?v=zUS5Qz1rP7U&t=0s&index=15&list=PLxC2MOV5xt5ap6DYRAO1cJeShqUGNdneH](url) shown "click" at "Browse server" button. Then opened file browser. In my situation - file browser empty.. :(

**Comment by pilot513** [comment]
Downgrade to php54 don't help me.

**Comment by pilot513** [comment]
**In FF (develop mode) log:**

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmresourcetype.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmfolders.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmactualfolder.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmresourceslist.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmupload.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmcreatefolder.html does not permit framing.

**Comment by turnermm** [comment]
https://stackoverflow.com/questions/38699221/load-denied-by-x-frame-options-does-not-permit-framing




Get Outlook for Android







On Thu, Mar 1, 2018 at 2:12 PM -0600, "pilot513" <notifications@github.com> wrote:












In FF (develop mode) log:


Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmresourcetype.html does not permit framing.

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmfolders.html does not permit framing.

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmactualfolder.html does not permit framing.

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmresourceslist.html does not permit framing.

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmupload.html does not permit framing.

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmcreatefolder.html does not permit framing.



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  









**In FF (develop mode) log:**

Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmresourcetype.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmfolders.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmactualfolder.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmresourceslist.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmupload.html does not permit framing.
Load denied by X-Frame-Options: https://doka.bss.nvg.ru/dokuwiki/lib/plugins/ckgdoku/fckeditor/editor/filemanager/browser/default/frmcreatefolder.html does not permit framing.

**Comment by pilot513** [comment]
Yes. I already find info: [https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/X-Frame-Options](url)

But in NEW FF (85.0.2) it's don't work... Yehhh . In Vivali - YES, confirmed, worked! 
May be any recepts for FF?

**Comment by pilot513** [comment]
So, and in IE (11.0.49) also don't worked

**Comment by pilot513** [comment]
checks for X-frames status [https://erlend.oftedal.no/blog/tools/xframeoptions/](url)

**Comment by pilot513** [comment]
![fail_02](https://user-images.githubusercontent.com/28645933/36869259-3c02d6e6-1dac-11e8-8098-f578e9a6320c.jpg)

**Comment by turnermm** [comment]
The problem is your web server. It does not allow frames: 

See: https://stackoverflow.com/questions/38699221/load-denied-by-x-frame-options-does-not-permit-framing

But you should be to switch over to the  native Dokuwiki media manager and linkwiz by clicking this button:
![dw filebrowserbutton](https://user-images.githubusercontent.com/176447/36869729-615082ee-1d62-11e8-84f2-feeaddee4a44.png)

Click the `DW Filebrowser` button.  That should not be using frames.  And then  you will get this:

![linkwiz](https://user-images.githubusercontent.com/176447/36870150-c02422e8-1d63-11e8-851d-2b47823d5ab6.png)

**Comment by pilot513** [comment]
Yes, that is right. But "DW Filebrowser" is not so convenient.  Thank you very much for help!
