### ISSUE TITLE
Cannot Save Page/Section with internalLink#Heading

### ISSUE THREAD

**Issue by steve-ohh** [turnermm/ckgedit#457]

**Comment by steve-ohh** [comment]
Hello ckgedit Team,

i have a problem with saving Pages or Sections wich contain a internal link. Here is a example:
First a create a new site with CKGEditor. It produces this Code:
`<h1 class="page-header">Just a heading</h1>

<div class="level1">
<p>just text</p>

<p><a class="wikilink1" href="http://lxopppdok01https://lxopppdok01/rswiki/doku.php?id=:test#just_a_heading" title="test">just a internal link to heading</a></p>
</div>`
I can save this and everything is fine.

Second, when i edit the Page/Section just to edit one simple thing I cannot save it anymore. It I have a look at the Source it automaticaly change to:
`<h1 class="page-header">Just a heading</h1>

<div class="level1">
<p>just text</p>

<p><a class="wikilink1 **curid" data-curid="true"** href="https://lxopppdok01/rswiki/doku.php?id=test#just_a_heading" title="test">just a internal link to heading</a></p>
</div>`

When I remove the 'curid" data-curid="true' part in Source then Saving is possible again. But after that the thing repeats on a next edit because the  'curid" data-curid="true' part is back in the code.

**Comment by turnermm** [comment]
I haven't been able to reproduce this error.  Give the precise steps you followed to get this result, in numbered order.  Also which version of dokuwiki are you using, which browser and operating system for the browser, which OS for your dokuwiki.

**Comment by Venice-89** [comment]
Hi,

I have the same issue. On some Dokuwiki artikles I am not able to save my changes.
If I click Save, the article is broken and I just got a page with the content "false"

I have to disable CKEdit for restoring the page via dokuwiki editor. 

I get the following error message in chrome after saving: 

=> Uncaught Parse Error: <a class="wikilink1 curid" data-curid="true" href="/doku.php?id=ist:gescho:start#XXX_XXX_XXX" title="ist:gescho:start">Arbeitsvertrag</a>).

**Comment by turnermm** [comment]
All that I can do is refer you to my previous comment.  And if I knew the content of the page that fails, that would be a great help.

**Comment by henrikhardt** [comment]
Hi, i have a similar problem and had to deactivate the plugin.

The "save" button is disabled. If i try to switch to "DW Edit" the page is corrupted. That means that the content is replaced by "false".

I just updated the plugin but it did not fix the problem. On the server-environment i had no changes / updates. I am not really sure but i think that i did not have the problem directly after installing the plugin.

I can reproduce the behavior with chrome / edge on Win10 an on actual iOS / IPad.

Dokuwiki: Release 2018-04-22b "Greebo"
ckgedit: 2019-02-28

The dokuwiki is running in a docker-container based on php:fpm-alpine with docker-container nginx:alpine in front of php.

I hope this helps. If needed i can give more information.

kind regards
Henrik

**Comment by turnermm** [comment]
There are other users who have had problems with using docker containers.  I have no experience with docker (or alpine) and am afraid I can't be of much help.

**Comment by henrikhardt** [comment]
Thx for the quick response. I tried to find the reason for the problem. Docker is not the problem.

I have a special network situation. We share one internet account for several server-> one external IP. To run several webservers / domains on 443 and 80 we use a sophos UTM (firewall) to split up the incoming requests (the domains server1.de and server2.de have the same public ip; sophos gets all requests to the public ip; it works as reverse proxy; server1.de > 192.168.x.y and server2 >192.168.a.b)

After adding the domain / local network IP of the dokuwiki webserver to my windows hosts file everything works fine. If i try to access from external ip the save-button of ckgedit does not work - there ist not reaction.

Conclusion --> there is an issue with the sophos utm config. If there are any known problems with this constellation (dokwiki /ckgedit behind firewall / reverse proxy) it would by nice if you can give me a hint.

Best Regards
Henrik

**Comment by turnermm** [comment]
I think I may have a solution which was contributed by another user who had what looks like this exact problem when behind a reverse proxy:

https://www.dokuwiki.org/plugin:ckgedit#reverse_proxy

**Comment by henrikhardt** [comment]
Thx, setting the baseurl and basedir fixed the problem.
Best regards
Henrik

**Comment by hibish123** [comment]
I am having the same problem as pointed out by @steve-ohh . 
I have created dokuwiki container using the following docker image(mprasil/dokuwiki:latest): [docker image](https://hub.docker.com/r/mprasil/dokuwiki/dockerfile)
DokuWiki version: Release 2018-04-22b "Greebo"
PHP version 7.0.33-0ubuntu0.16.04.1
Browser: Google Chrome
Operating System: Windows10
ckgedit: [Link to ckgedit I am using](https://www.dokuwiki.org/plugin:ckgedit)

The problem is I make changes using ckgedit plugin either to a page or a section, click Save button, but the Save button does not do anything i.e., I am still in edit mode. After looking into the source, I found the following:
`<li class="level3"><a class="wikilink2" href="/doku.php?id=controls:toolkit" rel="nofollow" title="controls:toolkit">MSI Toolkit</a></li>
		<li class="level3"><a class="wikilink1" href="/doku.php?id=controls:daqs" title="controls:daqs">DAQs</a></li>
		<li class="level3"><a class="wikilink2" href="/doku.php?id=controls:gmodel" rel="nofollow" title="controls:gmodel">Generation Model</a></li>
		<li class="level3"><a class="wikilink2" href="/doku.php?id=controls:optimizer" rel="nofollow" title="controls:optimizer">Optimizer</a></li>
		<li class="level3"><a class="wikilink1 curid" data-curid="true" href="/doku.php?id=controls:rids" title="controls:rids">RIDS</a></li>`
When I delete `curid" data-curid="true` , I am able to save but the problem comes back again when I use the ckgeditor. 
The Console shows:
`js.php?t=bootstrap3&tseed=72deffe359154f910dcdf2af4169fed0:1 Uncaught Parse Error: <a class="wikilink1 curid" data-curid="true" href="/doku.php?id=controls:rids" title="controls:rids">RIDS</a></li>`

I did set the baseurl and basedir as pointed out in the link above but that did not solve anything either. Any help would be highly appreciated.

**Comment by turnermm** [comment]
Of course, I could be missing something, but I can't see an error here.  Secondly, this syntax is not created by ckgedit but by dokuwiki.

**Comment by hibish123** [comment]
The problem is the fact that changes are not being saved. When I look into the console, this is the error I am getting as I mentioned above:
`Uncaught Parse Error: <a class="wikilink1 curid" data-curid="true" href="/doku.php?id=controls:rids" title="controls:rids">RIDS</a></li>`

Regarding the syntax, I have copied the syntax from Source and not ckgeditor. That is why you see dokuwiki syntax. I am switching to Source code and copying it because that is where I am able to see any changes that might lead me to the error. Otherwise ckgeditor is not showing any error as the page is just sitting there when I click Save button.

And as I mentioned above, I found the following when I switched from ckgeditor to Source:
` <li class="level3"><a class="wikilink1 curid" data-curid="true" href="/doku.php?id=controls:rids" title="controls:rids">RIDS</a></li>`
When I delete `curid" data-curid="true` , I am able to save but the problem comes back again when I use the ckgeditor again.

**Comment by turnermm** [comment]
You said you found this error in the console.  Are you now saying it is in the ckgedit source editor?  Can't be.  As I said before, ckgedit is not inserting the `data-curid` attribute.  That comes from dokuwiki.  Or from a plugin. Or  your template,  bootstrap3? If the ckeditor can't handle that, you can open an issue with CKEditor.

**Comment by turnermm** [comment]
Also, this is not the same issue as `Cannot Save Page/Section with internalLink#Heading`; it should have been created as a separate issue.

**Comment by petroser** [comment]
Hello colleagues,

I have with newest Dokuwiki and SKGEdit the exactly the same problem. The problem also disappeared, if I remove curid and data-curid="true".
So I just looked, where in code DokuWiki has data-curid and commented two strings out.
It seems to be bug/feature in bootstrap3, which however impact the systems with CKGEdit.

vi ./lib/tpl/bootstrap3/tpl_functions.php

function bootstrap3_content($content) {
.... skip ...
  # Move Current Page ID to <a> element and create data-curid HTML5 attribute
  foreach ($html->find('.curid') as $elm) {
    foreach ($elm->find('a') as $link) {
#      $link->class .= ' curid';
#      $link->attr[' data-curid'] = 'true'; # FIX attribute
    }
  }
.... skip ...

now it seems to work ...
Will observe the system next days ...
