### ISSUE TITLE
Latest version throws wiki errors

### ISSUE THREAD

**Issue by rivalsystems** [turnermm/ckgedit#577]
Just upgraded CKGEDIT to the newest version, and get errors when attempting to edit pages now

Im running hogfather, and the argon template

https://imgur.com/a/KHYz9Tp

I also get an error when attempting to save a change after all the errors above

parse_wiki-cmpr.js:1 Uncaught TypeError: HTMLParser is not a function
    at parse_wikitext (parse_wiki-cmpr.js:1)
    at HTMLInputElement.<anonymous> (parse_wiki-cmpr.js:1)
    at HTMLInputElement.dispatch (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
    at HTMLInputElement.v.handle (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)

**Comment by turnermm** [comment]
This is probably your problem: https://github.com/turnermm/ckgedit/issues/574#issuecomment-676834958
But there's nothing ckgedit can do about it.  And setting urls to canonical has other side effects. 

Also, I disabled ckgedit  because I noticed other non-ckgedit issues and found that the Argon template threw errors off other plugins as well.

**Comment by rivalsystems** [comment]
Yep that fixed it thank you!
