### ISSUE TITLE
Bad code block handling

### ISSUE THREAD

**Issue by srudakov** [turnermm/ckgedit#585]
If user inserts code block like
```
<code>
one
two
</code>
```

then after saving several empty lines will be added at the end of that code block.
And after new edit user will see `one` and `two` on same line and if he will change text in code block and save it, single line will remain.

**Comment by turnermm** [comment]
Use ckgedit's code block tool

**Comment by srudakov** [comment]
At first user creates code block, it looks like this
![creating_code_block](https://user-images.githubusercontent.com/23479423/95491695-a3a84d00-09a2-11eb-9c07-848f822f638e.png)

After save button page looks like this
![code_block_created](https://user-images.githubusercontent.com/23479423/95491714-adca4b80-09a2-11eb-9700-3ec54e27f4c2.png)

And on next edit try we have
![code_block_edit](https://user-images.githubusercontent.com/23479423/95492278-82942c00-09a3-11eb-9209-b062d7ae077c.png)

**Comment by turnermm** [comment]
I'm afraid I don't get the same result.  

1. Enter your initial text into the editor
2. Select the text
3. click on the code block icon
4. save
5. open page
6. enter text, using down arrow key to move to next line, not the Return key

The extra new-lines are needed, so that you can get back into the code block on re-loading the page for editing.  They should disappear when the page is displayed in the browser.  If not, there is not much I can do about it.  It could be caused by your system or by the way you are entering your text.
