### ISSUE TITLE
copy tables from libreofice calc

### ISSUE THREAD

**Issue by linvinus** [turnermm/ckgedit#66]
Hi!
Thanks for very useful plugin!
I have only one problem, when i copy paste tables from libreoffice calc, in editor table is ok, but after save table is broken.

 [![paste from libreoffice](http://storage1.static.itmages.ru/i/15/0204/s_1423077297_4149673_b812aa5b24.png)](http://itmages.ru/image/view/2252776/b812aa5b)

[![result after save](http://storage2.static.itmages.ru/i/15/0204/s_1423077546_7772992_7f258af7cf.png)](http://itmages.ru/image/view/2252781/7f258af7)

raw dokuwiki data http://pastebin.com/rb7BGHC9

as you can see, there is wrong line breaks and mistaken `</font>` tag

**Comment by linvinus** [comment]
by the way, copy paste from firefox working fine

**Comment by turnermm** [comment]
I have been able to copy and paste from web pages, as  here at:  [mturner.org](http://www.mturner.org/devel/doku.php?id=playground:copy_tables). But I probably did that using Firefox.  And I am able to copy and paste tables from Open Office spread sheets into both IE and Firefox.   Your problem seems to be coming from the font mechanism.  So, you may need to follow the [rules for fonts in ckgedit](https://www.dokuwiki.org/plugin:ckgedit#font_styling), the most important of which is to turn off the Scayt spell checker.  If that fails, then try to turn off all font styles in the table.

**Comment by turnermm** [comment]
Didn't mean to close this.

**Comment by linvinus** [comment]
The following settings do not help
```
$conf['plugin']['ckgedit']['scayt_auto'] = 'off';
$conf['plugin']['ckgedit']['nofont_styling'] = 1;
```
But i found button Tx which resets style, for me is enough.
