### ISSUE TITLE
Some Errors after installing with PHP 8.0.3 on Microsoft Server 2019 IIS

### ISSUE THREAD

**Issue by Gemeinde-Heidesee** [turnermm/ckgedit#688]
Hello,

ive installed the dokuwiki with chgedit on a Windows Server 2019 IIS with PHP 8.0.3.

Now i get some errors:

everywhere:
`Warning: Undefined array key "htmlok" in C:\inetpub\wwwroot\wiki\lib\plugins\ckgedit\action\meta.php on line 919`

and when i enter the CKEditor CSS Tool:
```
Warning: Undefined variable $ID in C:\inetpub\wwwroot\wiki\lib\plugins\ckgedit\admin.php on line 58

Warning: Undefined variable $data in C:\inetpub\wwwroot\wiki\lib\plugins\ckgedit\scripts\css6.php on line 469

Warning: Undefined variable $data in C:\inetpub\wwwroot\wiki\lib\plugins\ckgedit\scripts\css6.php on line 469

Warning: Undefined variable $data in C:\inetpub\wwwroot\wiki\lib\plugins\ckgedit\scripts\css6.php on line 469

Warning: Undefined variable $data in C:\inetpub\wwwroot\wiki\lib\plugins\ckgedit\scripts\css6.php on line 469
```

![grafik](https://user-images.githubusercontent.com/116711294/197963995-bf1de999-1958-4ab4-a2f0-c8c15c2fad4c.png)

can you help me to solve this problems?

**Comment by turnermm** [comment]
I've made a possible fix for the undefined htmlok.  I'm not sure why you are getting this; it doesn't occur in ubuntu. Please let me know your result.  When I hear back from you I will look at the other issues your.  
The fix is in the following branch:
https://github.com/turnermm/ckgedit/archive/refs/heads/winserv-php8-0.zip
You will have to install it using the manual tab of the extension manager.

 Thanks.

**Comment by Gemeinde-Heidesee** [comment]
Hello,

thanks for the feedback. But i have found a lot of other problems with this installation of dokuwiki...so i used another fresh installed IIS and there everything is working fine...
