### ISSUE TITLE
Browse images popup fails (incorrect url)

### ISSUE THREAD

**Issue by kjetilbmoe** [turnermm/ckgedit#69]
There is a questionmark too much in the url when adding images from server. It gives 403 error. I removed the questionmark following the two "connector.php" occurences in edit.php, and works fine then.

**Comment by turnermm** [comment]
Which browser are you using and on which Operating System?  And what is the Operating System of the server of which Dokuwiki is running?  And what is the name of your web server?

**Comment by kjetilbmoe** [comment]
For this I was running latest Chrome rpm on Fedora. I guess you figured the problem, but as you may know the url for the popup contains two question marks.

Browser dump: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36.

The server is hosted, but looks like it is RHEL 6, and web server is Apache.

**Comment by turnermm** [comment]
That second question mark shouldn't make a difference.

**Comment by turnermm** [comment]
I checked the CKEditor docs and there the final ```?``` is not included.   I've removed it and cite you in the Changelog.   The final  ```?``` has been there since the beginning, which is 2 years ago this month, and this is the first time it has been noted, and there seem to be many users    I have the same version of Chrome as you do, but on Windows, and I tried it in Ubuntu, but an earlier Chrome, and had no problems. In any event, if it doesn't belong there it shouldn't be there.
