### ISSUE TITLE
Content of page is deleted

### ISSUE THREAD

**Issue by teadawg** [turnermm/ckgedit#79]
If you edit a page in dokuwiki and click "DW Edit" to change the Editor, the content is deleted.

**Comment by turnermm** [comment]
You have to save your page before switching.

**Comment by teadawg** [comment]
I'm using the latest version of ckgedit and it is the default editor. However sometimes I prefer the DokuWiki-Editor, therefore I click on "DW-Edit" in ckgedit. I have not made any changes to the content, I just want to switch editor before I make any changes, but the complete content is replaced with "__false__" and saved.

**Comment by turnermm** [comment]
This is almost always a javascript issue. It could be your browser or a plugin.  So, first see what happens if you use a different browser.  If the problem persists, disable all plugins except for ckgedit to see if that's the source of the problem.  If it is, then re-enable them one at a time, to see where the conflict occurs.

**Comment by teadawg** [comment]
You were right. I just tried it in Safari and it works, before I used Firefox.

**Comment by Juergen-aus-Koeln** [comment]
A colleague of me had the same problem. Reason was the compatibility mode of the internet explorer, which has to be turned off.

**Comment by turnermm** [comment]
I am surprised that you had trouble with FireFox.  I have run ckgedit in FireFox on a wide variety of platforms, and have never had a problem.  And I just went through a whole series of tests to see if I could reproduce your problem and could not.  I assume you are on a Mac.  My tests on my own Mac, which is still at Snow Leopard, doesn't show any issues with the latest Firefox. I suspect in your case that there may still be a plugin conflict. 
As for IE -- I have to say that it's a relief to see that Microsoft is going to discontinue it with their next Windows upgrade.  The very fact that they have to offer users so many compatibility options shows how unreliable it is.

**Comment by jindrichmarek** [comment]
I think the bug is reproducible with recent Firefox (in my case on Windows 7 or Debian Linux) when you have both fckg and ckedit plugins installed and active. In that case when you use ckedit and then click the "DWedit" button, the word "_false_" replaces the whole text of the current wiki page. I thought before both plugins are needed because of the description of ckedit: "WYSIWYG editor upgrades fckgLite from FCKEditor to CKEditor". But when I deactivate fckg, the ckedit just works and no bug present... maybe the update of the description of ckedit and the mention of conflict with fckg (on Firefox) would help to prevent this bug.

**Comment by turnermm** [comment]
https://www.dokuwiki.org/plugin:ckgedit#installation
